### ISSUE TITLE
release of code?

### ISSUE THREAD

**Issue by TruthSearcher** [CodeGoat24/PrimeComposer#1]

**Comment by CodeGoat24** [comment]
Thank you for your interest in our work.

The code will be released after the paper is accepted.

**Comment by taierde111** [comment]
Will you not release the code if your work isn't accepted? Are you akin to Alibaba, practicing fake open source?

**Comment by CodeGoat24** [comment]
Thanks for your attention. 

We assure you that all the code will be made public immediately upon acceptance of the paper.
